Code review pull request
denigit5/Code_review_project pull request #1
Opened 2023-05-04 14:33 UTC by denigit5

2023-05-04 15:36 UTC, denigit5 reviewed
Changes Required♻

Please check all my comments below and make required changes.

Submit for a review when you're done.

Thanks😊

▪  Make use of the correct Github flow to generate checkers. 
▪   Update your ReadMe file in a professional way.
▪    Kindly ensure to commit the right message according to your files. In this case you style.css is committed with index.html content. Please be cautious in you next commits😄.


Feel free to leave a comment below but kindly remember to tag me so I can receive the notification😎.

2023-05-04 15:36 UTC, denigit5 commented on Index.html
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellend
You have done well up to this milestone, but according to Microserse requirements try to implement the Flexbox and Grid Css.  Give the main container the Flex property to be able to style the content in your works.

2023-05-04 15:36 UTC, denigit5 commented on Index.html
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellend
Please try to use the <ul> and <li> to list your items in the main container. This will help you style every container without having to style each container one at a time.

2023-05-04 15:36 UTC, denigit5 commented on style.css
> +  }
Please try to correct you code here(style your .nav-ul or omit it). It must have been an oversight :)

2023-05-08 08:08 UTC, aamirkhan2478 requested changes
Hi @denigit5 , 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort :+1: 
✔️ Your design is good. :+1: 
✔️ Good use of inline comments :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 08:08 UTC, aamirkhan2478 commented on Index.html
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellend
- [ ] As I mentioned above :point_up: please tell the student `why` we use `ul` and `li` then the student will understand more clearly :slightly_smiling_face:

2023-05-08 08:08 UTC, aamirkhan2478 commented on style.css
> +  }
- [ ] Please give more explanation and also tell the student why you give these required changes then the student will understand more clearly  :slightly_smiling_face:

2023-05-08 10:32 UTC, denigit5 commented on style.css
> +  }
@aamirkhan2478  Hello. Thank you for your review. Should I review the project again or just add comments on my current review?

2023-05-08 10:54 UTC, denigit5 commented
Hello.


Thank you for your review. Should I review the project again or just add
comments on my current review comments?


Best regards.


On Mon, 8 May 2023 at 11:08, Aamir khan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @denigit5 <https://github.com/denigit5> ,
>
>
> <https://camo.githubusercontent.com/9394efa3662ade294180d682ebade56334efde7f9b0ffaf2da4786d70e86ee0c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e6769663f6369643d65636630356534376b357561706470746730306e69646277337161787838697167737573676173776369326333756831267269643d67697068792e6769662663743d67>
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> ✔️ Good Effort 👍
> ✔️ Your design is good. 👍
> ✔️ Good use of inline comments 👍
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In Index.html
> <https://github.com/denigit5/Code_review_project/pull/1#discussion_r1187146595>
> :
>
> > +      <div class="container-post">
> +        <div class="title">
> +          <h1>Feature Products</h1>
> +        </div>
> +        <div class="post">
> +          <p class="box">
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellendus nam vero impedit ut aliquid?
> +          </p>
> +          <p class="box">
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellendus nam vero impedit ut aliquid?
> +          </p>
> +          <p class="box">
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellendus nam vero impedit ut aliquid?
>
>
>    - Well done 👏 you use inline comments 👍 but in suggestion, you
>    didn't tell why we use flexbox and grid css then the student will
>    understand more clearly 🙂
>
> ------------------------------
>
> In Index.html
> <https://github.com/denigit5/Code_review_project/pull/1#discussion_r1187148691>
> :
>
> > +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellendus nam vero impedit ut aliquid?
> +          </p>
> +          <p class="box">
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellendus nam vero impedit ut aliquid?
> +          </p>
> +          <p class="box">
> +            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto quo, dolorem saepe consequatur corrupti enim omnis quos ipsam mollitia pariatur sequi voluptatem amet veniam repellendus nam vero impedit ut aliquid?
>
>
>    - As I mentioned above ☝️ please tell the student why we use ul and li
>    then the student will understand more clearly 🙂
>
> ------------------------------
>
> In style.css
> <https://github.com/denigit5/Code_review_project/pull/1#discussion_r1187151603>
> :
>
> > +  }
> +  .nav-ul {
> +  }
>
>
>    - Please give more explanation and also tell the student why you give
>    these required changes then the student will understand more clearly 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/denigit5/Code_review_project/pull/1#pullrequestreview-1416316504>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2T47RASVW3WFUAHLRRAPNLXFCSX7ANCNFSM6AAAAAAXV4LSTQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-08 15:37 UTC, merged